-- Exécuter ce script dans l'éditeur SQL du dashboard Supabase (SQL Editor)

-- Table des favoris (recettes aimées par utilisateur)
create table if not exists public.favorites (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  recipe_id integer not null,
  created_at timestamptz default now(),
  unique(user_id, recipe_id)
);

-- Table des plannings sauvegardés
create table if not exists public.plannings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  label text,
  objective text,
  meals jsonb not null default '{}',
  created_at timestamptz default now()
);

-- RLS : chaque utilisateur n'accède qu'à ses données
alter table public.favorites enable row level security;
alter table public.plannings enable row level security;

drop policy if exists "Users can manage own favorites" on public.favorites;
create policy "Users can manage own favorites"
  on public.favorites for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can manage own plannings" on public.plannings;
create policy "Users can manage own plannings"
  on public.plannings for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Index pour les requêtes fréquentes
create index if not exists idx_favorites_user on public.favorites(user_id);
create index if not exists idx_plannings_user on public.plannings(user_id);

-- Table des recettes (contenu public)
create table if not exists public.recipes (
  id bigint primary key generated by default as identity,
  title text not null,
  category text not null,
  time int not null default 0,
  calories int not null default 0,
  protein int not null default 0,
  carbs int not null default 0,
  fat int not null default 0,
  servings int not null default 1,
  difficulty text not null default 'Facile',
  tags jsonb not null default '[]',
  objective jsonb not null default '[]',
  regime jsonb not null default '[]',
  season jsonb not null default '[]',
  main_ingredient text,
  image text,
  ingredients jsonb not null default '[]',
  steps jsonb not null default '[]',
  created_at timestamptz default now()
);

-- Table des articles du blog (contenu public)
create table if not exists public.blog_articles (
  id bigint primary key generated by default as identity,
  title text not null,
  excerpt text,
  meta_title text,
  meta_description text,
  category text not null,
  date date not null,
  read_time int not null default 5,
  image text,
  author text,
  content text,
  content_json jsonb,
  created_at timestamptz default now()
);

-- RLS : lecture publique pour recettes et articles
alter table public.recipes enable row level security;
alter table public.blog_articles enable row level security;

drop policy if exists "Recettes en lecture publique" on public.recipes;
create policy "Recettes en lecture publique"
  on public.recipes for select using (true);

drop policy if exists "Articles blog en lecture publique" on public.blog_articles;
create policy "Articles blog en lecture publique"
  on public.blog_articles for select using (true);

-- Index pour filtres et listes
create index if not exists idx_recipes_category on public.recipes(category);
create index if not exists idx_blog_articles_category on public.blog_articles(category);
create index if not exists idx_blog_articles_date on public.blog_articles(date desc);
