-- Article 3 : Menu végétarien sportif sur 7 jours
alter table public.blog_articles
  add column if not exists meta_title text,
  add column if not exists meta_description text,
  add column if not exists content_json jsonb;

do $$
begin
  if not exists (
    select 1 from public.blog_articles
    where title = 'Menu végétarien sportif sur 7 jours (simple et protéiné)'
  ) then
    insert into public.blog_articles (
      id, title, excerpt, meta_title, meta_description,
      category, date, read_time, image, author, content, content_json
    )
    overriding system value
    values (
      9,
      'Menu végétarien sportif sur 7 jours (simple et protéiné)',
      'Un menu végétarien sportif sur une semaine, simple, protéiné et adapté au quotidien, avec des idées de repas pour mieux s''entraîner et récupérer.',
      'Menu végétarien sportif sur 7 jours (simple et protéiné) | Et si mamie était végé ?',
      'Un menu végétarien sportif sur une semaine, simple, protéiné et adapté au quotidien, avec des idées de repas pour mieux s''entraîner et récupérer.',
      'Organisation',
      '2026-03-12'::date,
      12,
      'https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=600&h=400&fit=crop',
      'Maxence',
      '',
      '[
        {"type":"heading","level":1,"text":"Menu végétarien sportif sur une semaine : simple, protéiné et réaliste"},
        {"type":"paragraph","text":"Tu veux manger végétarien, faire du sport et éviter de te prendre la tête chaque jour devant le frigo. L''idée de ce menu sur 7 jours, c''est de te proposer une base simple, modulable, avec suffisamment de protéines et de bons glucides pour soutenir tes entraînements, sans passer ta vie en cuisine."},
        {"type":"paragraph","text":"Ce menu est une trame : à adapter à ton poids, ton appétit, ton niveau d''activité et ton sport. Tu peux aussi répéter certains plats que tu aimes pour simplifier."},
        {"type":"heading","level":2,"text":"Principes du menu sportif végétarien"},
        {"type":"paragraph","text":"Avant de détailler les jours, quelques principes pour garder l''équilibre :"},
        {"type":"list","items":["Chaque repas principal contient une source de protéines végétales (lentilles, pois chiches, tofu, tempeh, haricots rouges…).","On ajoute des glucides complexes (riz complet, pâtes complètes, quinoa, flocons d''avoine, pain complet) pour l''énergie.","On n''oublie pas les bonnes graisses (huile d''olive, colza, noix, graines, oléagineux).","On varie les légumes (crus et cuits) pour les fibres, vitamines et minéraux.","Pense aussi à boire régulièrement dans la journée, surtout si tu t''entraînes souvent."]},
        {"type":"heading","level":2,"text":"Jour 1 – Lundi (journée type « reprise de semaine »)"},
        {"type":"heading","level":3,"text":"Petit-déjeuner"},
        {"type":"paragraph","text":"Porridge : flocons d''avoine + boisson végétale + banane + une poignée d''amandes ou noix."},
        {"type":"heading","level":3,"text":"Déjeuner"},
        {"type":"paragraph","text":"Salade de lentilles vertes (lentilles, carottes, oignon rouge, persil) + pain complet. 1 fruit en dessert."},
        {"type":"heading","level":3,"text":"Snack / collation"},
        {"type":"paragraph","text":"Yaourt végétal (si possible enrichi en protéines) + quelques graines (courge ou tournesol)."},
        {"type":"heading","level":3,"text":"Dîner"},
        {"type":"paragraph","text":"Curry de pois chiches au lait de coco léger avec riz complet. Légumes verts (brocoli, haricots verts, épinards selon saison / surgelé)."},
        {"type":"heading","level":2,"text":"Jour 2 – Mardi (jour avec séance de sport prévue)"},
        {"type":"heading","level":3,"text":"Petit-déjeuner"},
        {"type":"paragraph","text":"Tartines de pain complet avec houmous + tomates / concombre. 1 fruit (par exemple une orange ou kiwi)."},
        {"type":"heading","level":3,"text":"Avant l''entraînement (si besoin)"},
        {"type":"paragraph","text":"1 fruit (banane ou pomme)."},
        {"type":"heading","level":3,"text":"Déjeuner"},
        {"type":"paragraph","text":"Bowl : quinoa + tofu mariné poêlé + légumes rôtis (carottes, poivrons, courgettes) + graines de sésame."},
        {"type":"heading","level":3,"text":"Collation post-entraînement"},
        {"type":"paragraph","text":"Smoothie : boisson végétale + fruit + 1 cuillère à soupe de purée d''oléagineux (cacahuète, amande, etc.)."},
        {"type":"heading","level":3,"text":"Dîner"},
        {"type":"paragraph","text":"Chili sin carne (haricots rouges, maïs, tomates, oignon, épices) + riz basmati ou complet. Salade verte simple en accompagnement."},
        {"type":"heading","level":2,"text":"Jour 3 – Mercredi (journée plus « posée » ou renfo léger)"},
        {"type":"heading","level":3,"text":"Petit-déjeuner"},
        {"type":"paragraph","text":"Muesli maison : flocons d''avoine, fruits secs, graines, quelques noix + yaourt végétal."},
        {"type":"heading","level":3,"text":"Déjeuner"},
        {"type":"paragraph","text":"Galettes de haricots blancs et flocons d''avoine (façon « steak ») + pommes de terre au four + salade de chou ou coleslaw léger."},
        {"type":"heading","level":3,"text":"Collation"},
        {"type":"paragraph","text":"1 fruit + une petite poignée de noix ou amandes."},
        {"type":"heading","level":3,"text":"Dîner"},
        {"type":"paragraph","text":"Pâtes complètes avec sauce lentilles corail (lentilles corail + tomates + carotte + oignon + herbes). Légumes (par exemple une ratatouille maison ou surgelée)."},
        {"type":"heading","level":2,"text":"Jour 4 – Jeudi (journée avec séance cardio / endurance)"},
        {"type":"heading","level":3,"text":"Petit-déjeuner"},
        {"type":"paragraph","text":"Porridge (flocons d''avoine + boisson végétale) avec fruits rouges (frais ou surgelés) + graines de chia ou de lin moulues."},
        {"type":"heading","level":3,"text":"Avant entraînement"},
        {"type":"paragraph","text":"1 banane ou 1 compote + éventuellement une petite poignée de fruits secs."},
        {"type":"heading","level":3,"text":"Déjeuner"},
        {"type":"paragraph","text":"Salade complète : pois chiches, boulgour ou couscous complet, tomates, concombre, poivrons, olives, herbes, huile d''olive."},
        {"type":"heading","level":3,"text":"Collation post-entraînement"},
        {"type":"paragraph","text":"1 yaourt végétal + 1 fruit."},
        {"type":"heading","level":3,"text":"Dîner"},
        {"type":"paragraph","text":"Tofu grillé ou tempeh avec riz complet et légumes vapeur (brocoli, carottes, petits pois). Un filet d''huile (olive ou colza) sur les légumes."},
        {"type":"heading","level":2,"text":"Jour 5 – Vendredi (jour « boulot + sport en fin de journée »)"},
        {"type":"heading","level":3,"text":"Petit-déjeuner"},
        {"type":"paragraph","text":"Tartines de pain complet + purée d''amande ou de cacahuète + rondelles de banane. 1 boisson chaude."},
        {"type":"heading","level":3,"text":"Déjeuner"},
        {"type":"paragraph","text":"Wraps végétariens : houmous, crudités (carottes, salade, concombre), tofu grillé ou haricots rouges, un peu de maïs."},
        {"type":"heading","level":3,"text":"Avant entraînement"},
        {"type":"paragraph","text":"1 fruit ou 1 petite barre céréalière maison (flocons + fruits secs)."},
        {"type":"heading","level":3,"text":"Collation post-entraînement"},
        {"type":"paragraph","text":"Smoothie (boisson végétale + fruit) + poignée d''oléagineux ou, si besoin, un petit shaker de protéines végétales."},
        {"type":"heading","level":3,"text":"Dîner"},
        {"type":"paragraph","text":"Poêlée de légumes de saison + pommes de terre ou patates douces rôties + pois chiches ou lentilles."},
        {"type":"heading","level":2,"text":"Jour 6 – Samedi (sortie longue ou séance plus longue)"},
        {"type":"heading","level":3,"text":"Petit-déjeuner"},
        {"type":"paragraph","text":"Bol « sportif » : flocons d''avoine + boisson végétale + yaourt végétal + fruits + graines (chanvre, tournesol…)."},
        {"type":"heading","level":3,"text":"Collation avant ou pendant l''effort (si sortie longue)"},
        {"type":"paragraph","text":"Banane, mélange maison de fruits secs et oléagineux, compote à boire."},
        {"type":"heading","level":3,"text":"Déjeuner"},
        {"type":"paragraph","text":"Buddha bowl : base riz complet ou quinoa, pois chiches rôtis ou tofu, légumes variés crus et cuits, sauce tahini-citron."},
        {"type":"heading","level":3,"text":"Collation"},
        {"type":"paragraph","text":"1 fruit + quelques noix."},
        {"type":"heading","level":3,"text":"Dîner"},
        {"type":"paragraph","text":"Soupe de légumes épaisse (avec lentilles ou pois cassés pour les protéines) + pain complet. Un peu de houmous ou tartinade de légumineuses sur le pain."},
        {"type":"heading","level":2,"text":"Jour 7 – Dimanche (jour « famille / repos actif »)"},
        {"type":"heading","level":3,"text":"Petit-déjeuner"},
        {"type":"paragraph","text":"Pancakes ou crêpes végétariennes (ou véganes) à base de farine complète, lait végétal, servis avec fruits et un peu de purée de noisette ou de cacahuète."},
        {"type":"heading","level":3,"text":"Déjeuner"},
        {"type":"paragraph","text":"Plat « façon mamie » revisité : par exemple hachis parmentier végétarien (lentilles ou protéines de soja texturées à la place de la viande) + purée de pommes de terre + légumes."},
        {"type":"heading","level":3,"text":"Collation"},
        {"type":"paragraph","text":"1 fruit ou une part de gâteau maison aux flocons d''avoine et fruits (sucre modéré)."},
        {"type":"heading","level":3,"text":"Dîner"},
        {"type":"paragraph","text":"Salade composée légère : mélange de feuilles vertes, restes de légumineuses (pois chiches ou lentilles), quelques noix, légumes de saison, vinaigrette maison."},
        {"type":"cta_planning"},
        {"type":"heading","level":2,"text":"Astuces pour t''organiser sur la semaine (batch cooking)"},
        {"type":"paragraph","text":"Pour que ce menu reste réaliste au quotidien, quelques astuces d''organisation peuvent tout changer :"},
        {"type":"list","items":["Cuire un gros volume de légumineuses (lentilles, pois chiches) en début de semaine et les utiliser dans plusieurs plats.","Préparer un gros bocal de houmous ou de tartinade de légumineuses pour les petits-déj salés, wraps et apéros.","Cuire du riz complet, quinoa ou pâtes complètes en quantité pour 2–3 jours.","Avoir toujours des légumes surgelés sous la main (brocoli, épinards, etc.) pour compléter un repas en 5 minutes."]},
        {"type":"paragraph","text":"Tu peux bien sûr adapter ce menu à ton contexte : ajouter un repas de plus si tu as un très gros appétit, doubler les portions après les séances longues, ou remplacer certains plats par ceux de l''article sur les recettes protéinées."}
      ]'::jsonb
    );
  end if;
end $$;
