-- Table centralisée des ingrédients (réutilisables entre recettes, avec rayon supermarché)
-- Permet à l’ajout de recettes de réutiliser les ingrédients existants et d’ajouter les nouveaux.
create table if not exists public.ingredients (
  id bigint primary key generated by default as identity,
  name text not null,
  rayon text not null default 'Fruits et légumes',
  created_at timestamptz default now(),
  unique(name)
);

comment on column public.ingredients.rayon is 'Rayon supermarché pour la liste de courses. Valeurs recommandées: Fruits et légumes, Épicerie, Pâtes riz et céréales, Boissons, Frais et protéines végétales, Surgelés, Condiments et épices, Graines et oléagineux';

-- Lien recette ↔ ingrédient avec quantité (texte libre : "80g", "1 c.à.s", etc.)
create table if not exists public.recipe_ingredients (
  recipe_id bigint not null references public.recipes(id) on delete cascade,
  ingredient_id bigint not null references public.ingredients(id) on delete restrict,
  quantity_text text not null default '',
  primary key (recipe_id, ingredient_id)
);

create index if not exists idx_recipe_ingredients_recipe on public.recipe_ingredients(recipe_id);
create index if not exists idx_recipe_ingredients_ingredient on public.recipe_ingredients(ingredient_id);
create index if not exists idx_ingredients_rayon on public.ingredients(rayon);

-- RLS : lecture publique pour ingrédients et recipe_ingredients (comme les recettes)
alter table public.ingredients enable row level security;
alter table public.recipe_ingredients enable row level security;

drop policy if exists "Ingredients en lecture publique" on public.ingredients;
create policy "Ingredients en lecture publique"
  on public.ingredients for select using (true);

drop policy if exists "Recipe ingredients en lecture publique" on public.recipe_ingredients;
create policy "Recipe ingredients en lecture publique"
  on public.recipe_ingredients for select using (true);

-- Note : les recettes gardent ingredients (jsonb) pour compatibilité. Une future interface
-- d’édition pourra utiliser ingredients + recipe_ingredients (sélection ou création d’ingrédients).
